version: '3'
services:
    mysql:
        image: 'fullstack_docker-mysql:latest'
        container_name: mysql_container
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - '0.0.0.0:3305:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - server_network

    mongo:
        image: 'fullstack_docker-mongo:latest'
        container_name: mongo_container
        ports:
            - '0.0.0.0:27017:27017'
        volumes:
            - mongo_data:/data/db

        networks:
            - server_network

    server:
        image: 'fullstack_docker-server:latest'
        container_name: server_container
        ports:
            - '0.0.0.0:2303:2303'
        networks:
            - server_network

    client:
        image: 'fullstack_docker-client:latest'
        container_name: client_container
        ports:
            - '0.0.0.0:3000:3000'
        networks:
            - server_network

networks:
    server_network:
        driver: bridge

volumes:
    mysql_data:
    mongo_data:
